// Generated by CoffeeScript 1.8.0
var RobotTestMachine, bot, timer_id,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RobotTestMachine = (function(_super) {
  __extends(RobotTestMachine, _super);

  function RobotTestMachine(driver) {
    this.driver = driver;
    this.entering = __bind(this.entering, this);
    this.listener = __bind(this.listener, this);
    RobotTestMachine.__super__.constructor.call(this, "ready", ["stop"]);
    this.limited = this.addChild(new RobotTimeLimit("limiting", [], 600));
    this.sequence = this.limited.addChild(new RobotSequentialState("stepping", ["go"]));
    this.sequence.addChild = (function(_this) {
      return function(state) {
        state.parent = _this.sequence;
        _this.sequence.behaviors.unshift(state);
        return state;
      };
    })(this);
    this.limited.addChild(new RobotFlaggingState("storing", ["store"], (function(_this) {
      return function(coords) {
        return _this.sequence.addChild(new RobotFindingState(_this.driver, "p", [], coords));
      };
    })(this)));
    this.driving = this.limited.addChild(new Driving("driving", ["drive"], this.driver, 5));
    this.resetting = this.addChild(new RobotState("resetting", ["reset"]));
    this.addChild(new RobotPhotographingState("shooting", ["shoot"], "picture1"));
    this.addChild(new CompassCalibrator("calibrating", ["calibrate"], this.driver));
    this.addChild(new CompassDisplay("compass", ["compass"]));
  }

  RobotTestMachine.prototype.listener = function(currentState, event) {
    if (currentState === this.resetting) {
      return new RobotTestMachine(this.driver);
    } else {
      return RobotTestMachine.__super__.listener.call(this, currentState, event);
    }
  };

  RobotTestMachine.prototype.entering = function(oldState, currentState) {
    if (currentState === this) {
      return this.driver.drive(0);
    }
  };

  return RobotTestMachine;

})(ButtonWatcher);

timer_id = null;

bot = new StateTracker(function(state, event) {
  var eventkey, eventval, html, lastevent;
  console.log("pushed state to " + state.name);
  lastevent = event ? (eventkey = Object.keys(event)[0], eventval = event[eventkey], " " + eventkey + ":" + eventval) : "";
  html = state.ancestor().accordian(state, lastevent);
  clearTimeout(timer_id);
  return timer_id = setTimeout((function(html) {
    return $("#set").html(html).collapsibleset("refresh");
  }), 1000, html);
});

$(function() {
  bot.setState(new RobotTestMachine(new BigCar(bot, 200)));
  bot.addAnnouncer(new ButtonAnnouncer("button", ["go", "stop", "store", "reset", "drive", "shoot", "calibrate", "compass"]));
  bot.addAnnouncer(new CrashAnnouncer("crash"));
  bot.addAnnouncer(new OrientationAnnouncer("orientation"));
  bot.addAnnouncer(new LocationAnnouncer("location"));
  return bot.addAnnouncer(new TimeAnnouncer("time"));
});
